// Copyright 2013-2019, University of Colorado Boulder

/**
 * Module that includes all Kite dependencies, so that requiring this module will return an object
 * that consists of the entire exported 'kite' namespace API.
 *
 * The API is actually generated by the 'kite' module, so if this module (or all other modules) are
 * not included, the 'kite' namespace may not be complete.
 *
 * @author Jonathan Olson <jonathan.olson@colorado.edu>
 */

define( require => {

  'use strict';

  const kite = require( 'KITE/kite' );

  require( 'KITE/Shape' );
  require( 'KITE/ops/Boundary' );
  require( 'KITE/ops/BoundsIntersection' );
  require( 'KITE/ops/Edge' );
  require( 'KITE/ops/Face' );
  require( 'KITE/ops/Graph' );
  require( 'KITE/ops/HalfEdge' );
  require( 'KITE/ops/Loop' );
  require( 'KITE/ops/Vertex' );
  require( 'KITE/segments/Arc' );
  require( 'KITE/segments/Cubic' );
  require( 'KITE/segments/EllipticalArc' );
  require( 'KITE/segments/Line' );
  require( 'KITE/segments/Quadratic' );
  require( 'KITE/segments/Segment' );
  require( 'KITE/util/LineStyles' );
  require( 'KITE/util/Overlap' );
  require( 'KITE/util/SegmentIntersection' );
  require( 'KITE/util/Subpath' );

  require( 'KITE/parser/svgPath' );

  // note: the kite variable is filled in as modules are visited
  return kite;
} );
